
server:
  port: 0

spring:
  application:
    name: pagamentos-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
      url: jdbc:postgresql://localhost:5432/ecommerce
      username: postgres
      password: 1234
  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

gateway:
  host: ${gateway.host:localhost:8082}