
server:
  port: 8080

spring:
  jpa:
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASS}
