version: "3.1"
services:
  mongo-auth:
    image: mongo
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=storeDb

  ecommerce-postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"

  eureka-server:
    image: pradoo159/eureka-service:1.0
    ports:
      - "8761:8761"

  gateway:
    image: pradoo159/gateway:1.0
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

  cadastro:
    image: pradoo159/cadastro:1.0
    depends_on:
      - mongo-auth
      - eureka-server
      - gateway
    environment:
      - mongodb.host=mongo-auth
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

  autenticacao:
    image: pradoo159/autenticacao:1.0
    depends_on:
      - mongo-auth
      - eureka-server
      - gateway
    environment:
      - mongodb.host=mongo-auth
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

  produto:
    image: pradoo159/produto:1.0
    depends_on:
      - mongo-auth
      - eureka-server
      - gateway
    environment:
      - mongodb.host=mongo-auth
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

  pagamentos:
    image: pradoo159/pagamentos:1.0
    depends_on:
      - mongo-auth
      - eureka-server
      - gateway
      - ecommerce-postgresql
      - produto
    environment:
      - mongodb.host=mongo-auth
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - gateway.host=http://gateway:8082
      - spring.datasource.url=jdbc:postgresql://ecommerce-postgresql:5432/ecommerce
